#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'capify', :git => 'git@github.com:openteam/cookbook-capify.git'
cookbook 'rvm',    :git => 'git@github.com:openteam/cookbook-rvm.git'
cookbook 'nodejs', :git => 'git@github.com:openteam/cookbook-nodejs.git'
